#!/usr/bin/env node
/**
 * Builds CSS custom properties and TypeScript defs from DTCG token sources.
 * Supports light/dark modes via $extensions.mode.
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SOURCE_DIR = join(ROOT, 'src/tokens/source');
const OUT_DIR = join(ROOT, 'src/tokens/generated');

function loadAllTokens() {
  const files = readdirSync(SOURCE_DIR).filter((f) => f.endsWith('.tokens.json'));
  const merged = {};
  for (const file of files) {
    const data = JSON.parse(readFileSync(join(SOURCE_DIR, file), 'utf-8'));
    Object.assign(merged, data);
  }
  return merged;
}

function flattenTokens(obj, prefix = []) {
  const result = [];
  for (const [key, value] of Object.entries(obj)) {
    const path = [...prefix, key];
    if (value && typeof value === 'object' && '$value' in value) {
      result.push({ path, token: value });
    } else if (value && typeof value === 'object') {
      result.push(...flattenTokens(value, path));
    }
  }
  return result;
}

function pathToCssVar(path) {
  return '--' + path.join('-');
}

function resolveRef(value, primitives, chain = new Set()) {
  if (typeof value !== 'string') return value;
  if (!value.startsWith('{') || !value.endsWith('}')) return value;
  const ref = value.slice(1, -1);
  if (chain.has(ref)) throw new Error(`Circular reference: ${ref}`);
  chain.add(ref);
  const parts = ref.split('.');
  let current = primitives;
  for (const part of parts) {
    current = current?.[part];
    if (!current) throw new Error(`Unresolved reference: ${value}`);
  }
  if (current.$value) {
    return resolveRef(current.$value, primitives, chain);
  }
  return current;
}

function buildPrimitiveMap(primitivesRoot) {
  const flat = {};
  function walk(obj, prefix) {
    for (const [key, value] of Object.entries(obj)) {
      const path = [...prefix, key];
      if (value?.$value !== undefined) {
        flat[path.join('.')] = value.$value;
      } else if (value && typeof value === 'object') {
        walk(value, path);
      }
    }
  }
  walk(primitivesRoot, []);
  return flat;
}

function resolveTokenValue(raw, primitiveFlat) {
  if (typeof raw !== 'string') return raw;
  if (raw.startsWith('{')) {
    let ref = raw.slice(1, -1);
    if (ref.startsWith('primitives.')) ref = ref.slice('primitives.'.length);
    const resolved = primitiveFlat[ref];
    if (resolved === undefined) throw new Error(`Unresolved: ${raw}`);
    return resolved;
  }
  return raw;
}

function main() {
  const tokens = loadAllTokens();
  const primitiveFlat = buildPrimitiveMap(tokens.primitives || {});
  const flat = flattenTokens(tokens);

  const lightVars = {};
  const darkVars = {};
  const cssVarNames = [];

  for (const { path, token } of flat) {
    if (path[0] === 'primitives') continue;
    if (token.$type === 'color' || token.$type === 'number') {
      const cssName = pathToCssVar(path);
      cssVarNames.push(cssName.slice(2));

      const modes = token.$extensions?.mode;
      const lightRaw = modes?.light ?? token.$value;
      const darkRaw = modes?.dark ?? token.$value;

      lightVars[cssName] = resolveTokenValue(lightRaw, primitiveFlat);
      darkVars[cssName] = resolveTokenValue(darkRaw, primitiveFlat);
    }
  }

  // Primitives as CSS vars (--primitives-* namespace)
  const primitiveLines = [];
  for (const [ref, hex] of Object.entries(primitiveFlat)) {
    primitiveLines.push(`  --primitives-${ref.replace(/\./g, '-')}: ${hex};`);
  }

  const semanticLines = Object.entries(lightVars)
    .filter(([name]) => !name.startsWith('--primitives-'))
    .map(([name, val]) => {
      const primRef = flat.find((f) => pathToCssVar(f.path) === name);
      const lightRaw = primRef?.token.$extensions?.mode?.light ?? primRef?.token.$value;
      if (typeof lightRaw === 'string' && lightRaw.startsWith('{')) {
        return `  ${name}: var(--${lightRaw.slice(1, -1).replace(/\./g, '-')});`;
      }
      return `  ${name}: ${val};`;
    });

  const darkSemanticEntries = Object.entries(darkVars).filter(
    ([name]) => !name.startsWith('--primitives-') && darkVars[name] !== lightVars[name]
  );

  const darkLines = darkSemanticEntries.map(([name, val]) => {
    const primRef = flat.find((f) => pathToCssVar(f.path) === name);
    const darkRaw = primRef?.token.$extensions?.mode?.dark ?? primRef?.token.$value;
    if (typeof darkRaw === 'string' && darkRaw.startsWith('{')) {
      return `    ${name}: var(--${darkRaw.slice(1, -1).replace(/\./g, '-')});`;
    }
    return `    ${name}: ${val};`;
  });

  const css = `/**
 * Design Tokens - Generated from DTCG Source
 * DO NOT EDIT - auto-generated by scripts/build-tokens.mjs
 *
 * Source: src/tokens/source/*.tokens.json
 * Figma: 1. Color modes collection (273 tokens)
 */

:root {
  /* Primitives */
${primitiveLines.join('\n')}

  /* Semantic Tokens - Light Mode (Default) */
${semanticLines.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkLines.join('\n')}
  }
}

[data-theme="dark"] {
${darkLines.map((l) => l.replace(/^    /, '  ')).join('\n')}
}

[data-theme="light"] {
${semanticLines.join('\n')}
}
`;

  const dts = `/**
 * Design Token CSS Custom Properties
 * Auto-generated — do not edit
 */

export type TokenName =
${cssVarNames.map((n) => `  | '${n}'`).join('\n')};

export const tokenNames: TokenName[] = [
${cssVarNames.map((n) => `  '${n}',`).join('\n')}
];
`;

  writeFileSync(join(OUT_DIR, 'tokens.css'), css);
  writeFileSync(join(OUT_DIR, 'tokens.d.ts'), dts);
  console.log(`Built ${cssVarNames.length} semantic tokens + ${Object.keys(primitiveFlat).length} primitives`);
}

main();
